# Generated by Django 5.0 on 2024-01-04 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0001_squashed_0003_alter_userstory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
